version: "3.2"
services:
  elastic_serch:
    container_name: es01
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.4
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - data01:/usr/share/elasticsearch/data
volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge